package org.star_pet_house_commons.model.response;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Data;
import org.star_pet_house_commons.utils.DateStandardFormateSerializer;

import java.io.Serializable;
import java.util.Date;

@Data
@TableName(value = "log_application")
public class LogApplicationVO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_application.id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_application.store_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String store_id;

    private String store_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_application.accept_user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer accept_user_id;

    private String user_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_application.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    @JsonSerialize(using = DateStandardFormateSerializer.class)
    private Date create_datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_application.application_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String application_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_application.application_info
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String application_info;

}