package org.star_pet_house_commons.model.response;

import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Data;
import org.star_pet_house_commons.utils.DateStandardFormateSerializer;

import java.io.Serializable;
import java.util.Date;

@Data
@TableName(value = "log_complain")
public class LogComplainVO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_complain.serial_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    @TableId(value = "serial_no")
    private Integer serial_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_complain.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String user_id;

    private String user_name;

    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_complain.store_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String store_id;

    private String store_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_complain.sorder_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String sorder_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_complain.info
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_complain.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    @JsonSerialize(using = DateStandardFormateSerializer.class)
    private Date create_datetime;


}