package org.star_pet_house_commons.model.response;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Data;
import org.star_pet_house_commons.utils.DateStandardFormateSerializer;

import java.io.Serializable;
import java.util.Date;

@Data
@TableName(value = "log_login")
public class LogLoginVO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_login.serial_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    @TableId(value = "serial_no", type = IdType.AUTO)
    private Integer serial_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_login.occur_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    @JsonSerialize(using = DateStandardFormateSerializer.class)
    private Date occur_datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_login.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String user_id;

    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_login.nick_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String nick_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_login.ip_address
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String ip_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_login.login_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    @JsonSerialize(using = DateStandardFormateSerializer.class)
    private Date login_datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_login.error_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String error_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_login.error_info
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String error_info;

}