package org.star_pet_house_commons.model.response;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Data;
import org.star_pet_house_commons.utils.DateStandardFormateSerializer;

import java.io.Serializable;
import java.util.Date;

@Data
@TableName(value = "log_wallet")
public class LogWalletVO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_wallet.serial_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    @TableId(value = "serial_no", type = IdType.AUTO)
    private Integer serial_no;

    private String wallet_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_wallet.sorder_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String sorder_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_wallet.title
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_wallet.from_user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer from_user_id;

    private String from_user_name;

    private String from_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_wallet.to_user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer to_user_id;

    private String to_user_name;

    private String to_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_wallet.money
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Long money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_wallet.error_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String error_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_wallet.error_info
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String error_info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_wallet.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    @JsonSerialize(using = DateStandardFormateSerializer.class)
    private Date create_datetime;

}