package org.star_pet_house_commons.model.response;

import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Data;
import org.star_pet_house_commons.utils.DateStandardFormateSerializer;

import java.io.Serializable;
import java.util.Date;

@Data
@TableName(value = "user_info")
public class UserInfoVO implements Serializable {
    //序列化ID
    private static final long serialVersionUID = -5809782578272943999L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String user_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_image_url
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String user_image_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_gender
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String user_gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_age
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String user_age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_mobile_tel
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String user_mobile_tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id_card
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String user_id_card;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_address
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String user_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memo
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    @JsonSerialize(using = DateStandardFormateSerializer.class)
    private Date create_datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date update_datetime;

    private String status;

    private String user_status;

}