package org.star_pet_house_commons.model;

public class AllCityInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_city_info.id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_city_info.province_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String provinceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_city_info.province_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_city_info.city_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String cityNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_city_info.city_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_city_info.district_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String districtNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_city_info.district_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String districtName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_city_info.id
     *
     * @return the value of all_city_info.id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_city_info.id
     *
     * @param id the value for all_city_info.id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_city_info.province_no
     *
     * @return the value of all_city_info.province_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getProvinceNo() {
        return provinceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_city_info.province_no
     *
     * @param provinceNo the value for all_city_info.province_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setProvinceNo(String provinceNo) {
        this.provinceNo = provinceNo == null ? null : provinceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_city_info.province_name
     *
     * @return the value of all_city_info.province_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_city_info.province_name
     *
     * @param provinceName the value for all_city_info.province_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_city_info.city_no
     *
     * @return the value of all_city_info.city_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getCityNo() {
        return cityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_city_info.city_no
     *
     * @param cityNo the value for all_city_info.city_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setCityNo(String cityNo) {
        this.cityNo = cityNo == null ? null : cityNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_city_info.city_name
     *
     * @return the value of all_city_info.city_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_city_info.city_name
     *
     * @param cityName the value for all_city_info.city_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_city_info.district_no
     *
     * @return the value of all_city_info.district_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getDistrictNo() {
        return districtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_city_info.district_no
     *
     * @param districtNo the value for all_city_info.district_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setDistrictNo(String districtNo) {
        this.districtNo = districtNo == null ? null : districtNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_city_info.district_name
     *
     * @return the value of all_city_info.district_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_city_info.district_name
     *
     * @param districtName the value for all_city_info.district_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName == null ? null : districtName.trim();
    }
}