package org.star_pet_house_commons.model;

import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

@Data
@TableName(value = "all_city_code")
public class AllCityCode {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_city_info.province_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String province_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_city_info.province_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String province_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_city_info.city_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String city_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_city_info.city_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String city_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_city_info.district_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String district_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_city_info.district_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String district_name;

    private String default_level_no;

}