package org.star_pet_house_commons.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.util.Date;

@Data
@TableName(value = "log_application")
public class LogApplication {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_application.id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_application.store_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer store_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_application.accept_user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer accept_user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_application.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date create_datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_application.application_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String application_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_application.application_info
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String application_info;

}