package org.star_pet_house_commons.model;

import java.util.Date;

public class LogApplication {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_application.id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_application.store_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_application.accept_user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer acceptUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_application.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_application.application_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String applicationNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_application.application_info
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String applicationInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_application.id
     *
     * @return the value of log_application.id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_application.id
     *
     * @param id the value for log_application.id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_application.store_id
     *
     * @return the value of log_application.store_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_application.store_id
     *
     * @param storeId the value for log_application.store_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_application.accept_user_id
     *
     * @return the value of log_application.accept_user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getAcceptUserId() {
        return acceptUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_application.accept_user_id
     *
     * @param acceptUserId the value for log_application.accept_user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setAcceptUserId(Integer acceptUserId) {
        this.acceptUserId = acceptUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_application.create_datetime
     *
     * @return the value of log_application.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_application.create_datetime
     *
     * @param createDatetime the value for log_application.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_application.application_no
     *
     * @return the value of log_application.application_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getApplicationNo() {
        return applicationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_application.application_no
     *
     * @param applicationNo the value for log_application.application_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setApplicationNo(String applicationNo) {
        this.applicationNo = applicationNo == null ? null : applicationNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_application.application_info
     *
     * @return the value of log_application.application_info
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getApplicationInfo() {
        return applicationInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_application.application_info
     *
     * @param applicationInfo the value for log_application.application_info
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setApplicationInfo(String applicationInfo) {
        this.applicationInfo = applicationInfo == null ? null : applicationInfo.trim();
    }
}