package org.star_pet_house_commons.model;

import java.util.Date;

public class LogComplain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_complain.serial_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_complain.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_complain.store_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_complain.sorder_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String sorderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_complain.info
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_complain.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date createDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_complain.serial_no
     *
     * @return the value of log_complain.serial_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_complain.serial_no
     *
     * @param serialNo the value for log_complain.serial_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setSerialNo(Integer serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_complain.user_id
     *
     * @return the value of log_complain.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_complain.user_id
     *
     * @param userId the value for log_complain.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_complain.store_id
     *
     * @return the value of log_complain.store_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_complain.store_id
     *
     * @param storeId the value for log_complain.store_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_complain.sorder_no
     *
     * @return the value of log_complain.sorder_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getSorderNo() {
        return sorderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_complain.sorder_no
     *
     * @param sorderNo the value for log_complain.sorder_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setSorderNo(String sorderNo) {
        this.sorderNo = sorderNo == null ? null : sorderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_complain.info
     *
     * @return the value of log_complain.info
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_complain.info
     *
     * @param info the value for log_complain.info
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_complain.create_datetime
     *
     * @return the value of log_complain.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_complain.create_datetime
     *
     * @param createDatetime the value for log_complain.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }
}