package org.star_pet_house_commons.model;

import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.util.Date;
@Data
@TableName(value = "log_complain")
public class LogComplain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_complain.serial_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    @TableId(value = "serial_no")
    private Integer serial_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_complain.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_complain.store_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer store_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_complain.sorder_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String sorder_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_complain.info
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_complain.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date create_datetime;


}