package org.star_pet_house_commons.model;

import java.util.Date;

public class LogLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_login.serial_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_login.occur_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date occurDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_login.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_login.nick_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_login.ip_address
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String ipAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_login.login_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date loginDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_login.error_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String errorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_login.error_info
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String errorInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_login.serial_no
     *
     * @return the value of log_login.serial_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_login.serial_no
     *
     * @param serialNo the value for log_login.serial_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setSerialNo(Integer serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_login.occur_datetime
     *
     * @return the value of log_login.occur_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Date getOccurDatetime() {
        return occurDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_login.occur_datetime
     *
     * @param occurDatetime the value for log_login.occur_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setOccurDatetime(Date occurDatetime) {
        this.occurDatetime = occurDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_login.user_id
     *
     * @return the value of log_login.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_login.user_id
     *
     * @param userId the value for log_login.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_login.nick_name
     *
     * @return the value of log_login.nick_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_login.nick_name
     *
     * @param nickName the value for log_login.nick_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_login.ip_address
     *
     * @return the value of log_login.ip_address
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_login.ip_address
     *
     * @param ipAddress the value for log_login.ip_address
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_login.login_datetime
     *
     * @return the value of log_login.login_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Date getLoginDatetime() {
        return loginDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_login.login_datetime
     *
     * @param loginDatetime the value for log_login.login_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setLoginDatetime(Date loginDatetime) {
        this.loginDatetime = loginDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_login.error_no
     *
     * @return the value of log_login.error_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getErrorNo() {
        return errorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_login.error_no
     *
     * @param errorNo the value for log_login.error_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setErrorNo(String errorNo) {
        this.errorNo = errorNo == null ? null : errorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_login.error_info
     *
     * @return the value of log_login.error_info
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getErrorInfo() {
        return errorInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_login.error_info
     *
     * @param errorInfo the value for log_login.error_info
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setErrorInfo(String errorInfo) {
        this.errorInfo = errorInfo == null ? null : errorInfo.trim();
    }
}