package org.star_pet_house_commons.model;

import java.util.Date;

public class LogWallet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_wallet.serial_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_wallet.sorder_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String sorderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_wallet.title
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_wallet.from_user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer fromUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_wallet.to_user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer toUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_wallet.money
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Long money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_wallet.error_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String errorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_wallet.error_info
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String errorInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_wallet.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date createDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_wallet.serial_no
     *
     * @return the value of log_wallet.serial_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_wallet.serial_no
     *
     * @param serialNo the value for log_wallet.serial_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setSerialNo(Integer serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_wallet.sorder_no
     *
     * @return the value of log_wallet.sorder_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getSorderNo() {
        return sorderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_wallet.sorder_no
     *
     * @param sorderNo the value for log_wallet.sorder_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setSorderNo(String sorderNo) {
        this.sorderNo = sorderNo == null ? null : sorderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_wallet.title
     *
     * @return the value of log_wallet.title
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_wallet.title
     *
     * @param title the value for log_wallet.title
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_wallet.from_user_id
     *
     * @return the value of log_wallet.from_user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_wallet.from_user_id
     *
     * @param fromUserId the value for log_wallet.from_user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setFromUserId(Integer fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_wallet.to_user_id
     *
     * @return the value of log_wallet.to_user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_wallet.to_user_id
     *
     * @param toUserId the value for log_wallet.to_user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setToUserId(Integer toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_wallet.money
     *
     * @return the value of log_wallet.money
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Long getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_wallet.money
     *
     * @param money the value for log_wallet.money
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setMoney(Long money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_wallet.error_no
     *
     * @return the value of log_wallet.error_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getErrorNo() {
        return errorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_wallet.error_no
     *
     * @param errorNo the value for log_wallet.error_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setErrorNo(String errorNo) {
        this.errorNo = errorNo == null ? null : errorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_wallet.error_info
     *
     * @return the value of log_wallet.error_info
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getErrorInfo() {
        return errorInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_wallet.error_info
     *
     * @param errorInfo the value for log_wallet.error_info
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setErrorInfo(String errorInfo) {
        this.errorInfo = errorInfo == null ? null : errorInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_wallet.create_datetime
     *
     * @return the value of log_wallet.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_wallet.create_datetime
     *
     * @param createDatetime the value for log_wallet.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }
}