package org.star_pet_house_commons.model;

import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
@TableName(value = "pet_advice")
public class PetAdvice implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_advice.id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    @TableId(value = "id")
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_advice.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_advice.title
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_advice.author
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_advice.content
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_advice.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date create_datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_advice.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date update_datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_advice.advice_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String advice_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_advice.note
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String note;

}