package org.star_pet_house_commons.model;

import java.util.Date;

public class PetAdvice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_advice.id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_advice.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_advice.title
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_advice.author
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_advice.content
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_advice.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_advice.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_advice.advice_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String adviceStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_advice.note
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_advice.id
     *
     * @return the value of pet_advice.id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_advice.id
     *
     * @param id the value for pet_advice.id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_advice.user_id
     *
     * @return the value of pet_advice.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_advice.user_id
     *
     * @param userId the value for pet_advice.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_advice.title
     *
     * @return the value of pet_advice.title
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_advice.title
     *
     * @param title the value for pet_advice.title
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_advice.author
     *
     * @return the value of pet_advice.author
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_advice.author
     *
     * @param author the value for pet_advice.author
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_advice.content
     *
     * @return the value of pet_advice.content
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_advice.content
     *
     * @param content the value for pet_advice.content
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_advice.create_datetime
     *
     * @return the value of pet_advice.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_advice.create_datetime
     *
     * @param createDatetime the value for pet_advice.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_advice.update_datetime
     *
     * @return the value of pet_advice.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_advice.update_datetime
     *
     * @param updateDatetime the value for pet_advice.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_advice.advice_status
     *
     * @return the value of pet_advice.advice_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getAdviceStatus() {
        return adviceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_advice.advice_status
     *
     * @param adviceStatus the value for pet_advice.advice_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setAdviceStatus(String adviceStatus) {
        this.adviceStatus = adviceStatus == null ? null : adviceStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_advice.note
     *
     * @return the value of pet_advice.note
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_advice.note
     *
     * @param note the value for pet_advice.note
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}