package org.star_pet_house_commons.model;

import java.util.Date;

public class PetFund {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_fund.id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_fund.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_fund.title
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_fund.author
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_fund.pet_type
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String petType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_fund.pet_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String petName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_fund.pet_image_url
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String petImageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_fund.pet_description
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String petDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_fund.province_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String provinceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_fund.city_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String cityNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_fund.district_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String districtNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_fund.address
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_fund.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_fund.pet_fund_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String petFundStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_fund.contact_way
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private byte[] contactWay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_fund.id
     *
     * @return the value of pet_fund.id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_fund.id
     *
     * @param id the value for pet_fund.id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_fund.user_id
     *
     * @return the value of pet_fund.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_fund.user_id
     *
     * @param userId the value for pet_fund.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_fund.title
     *
     * @return the value of pet_fund.title
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_fund.title
     *
     * @param title the value for pet_fund.title
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_fund.author
     *
     * @return the value of pet_fund.author
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_fund.author
     *
     * @param author the value for pet_fund.author
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_fund.pet_type
     *
     * @return the value of pet_fund.pet_type
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getPetType() {
        return petType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_fund.pet_type
     *
     * @param petType the value for pet_fund.pet_type
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setPetType(String petType) {
        this.petType = petType == null ? null : petType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_fund.pet_name
     *
     * @return the value of pet_fund.pet_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getPetName() {
        return petName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_fund.pet_name
     *
     * @param petName the value for pet_fund.pet_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setPetName(String petName) {
        this.petName = petName == null ? null : petName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_fund.pet_image_url
     *
     * @return the value of pet_fund.pet_image_url
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getPetImageUrl() {
        return petImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_fund.pet_image_url
     *
     * @param petImageUrl the value for pet_fund.pet_image_url
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setPetImageUrl(String petImageUrl) {
        this.petImageUrl = petImageUrl == null ? null : petImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_fund.pet_description
     *
     * @return the value of pet_fund.pet_description
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getPetDescription() {
        return petDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_fund.pet_description
     *
     * @param petDescription the value for pet_fund.pet_description
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setPetDescription(String petDescription) {
        this.petDescription = petDescription == null ? null : petDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_fund.province_no
     *
     * @return the value of pet_fund.province_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getProvinceNo() {
        return provinceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_fund.province_no
     *
     * @param provinceNo the value for pet_fund.province_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setProvinceNo(String provinceNo) {
        this.provinceNo = provinceNo == null ? null : provinceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_fund.city_no
     *
     * @return the value of pet_fund.city_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getCityNo() {
        return cityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_fund.city_no
     *
     * @param cityNo the value for pet_fund.city_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setCityNo(String cityNo) {
        this.cityNo = cityNo == null ? null : cityNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_fund.district_no
     *
     * @return the value of pet_fund.district_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getDistrictNo() {
        return districtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_fund.district_no
     *
     * @param districtNo the value for pet_fund.district_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setDistrictNo(String districtNo) {
        this.districtNo = districtNo == null ? null : districtNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_fund.address
     *
     * @return the value of pet_fund.address
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_fund.address
     *
     * @param address the value for pet_fund.address
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_fund.create_datetime
     *
     * @return the value of pet_fund.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_fund.create_datetime
     *
     * @param createDatetime the value for pet_fund.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_fund.pet_fund_status
     *
     * @return the value of pet_fund.pet_fund_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getPetFundStatus() {
        return petFundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_fund.pet_fund_status
     *
     * @param petFundStatus the value for pet_fund.pet_fund_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setPetFundStatus(String petFundStatus) {
        this.petFundStatus = petFundStatus == null ? null : petFundStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_fund.contact_way
     *
     * @return the value of pet_fund.contact_way
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public byte[] getContactWay() {
        return contactWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_fund.contact_way
     *
     * @param contactWay the value for pet_fund.contact_way
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setContactWay(byte[] contactWay) {
        this.contactWay = contactWay;
    }
}