package org.star_pet_house_commons.model;

import java.util.Date;

public class PetItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.pet_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer petId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.pet_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String petName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.pet_description
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String petDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.pet_image_url
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String petImageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.pet_prime_cost
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Long petPrimeCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.pet_discount_price
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Long petDiscountPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.pet_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String petStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.pet_type
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String petType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.sale_type
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String saleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.contact_way
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String contactWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.city_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String cityNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.province_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String provinceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.district_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String districtNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.address
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.store_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_item.pet_id
     *
     * @return the value of pet_item.pet_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_item.pet_id
     *
     * @param petId the value for pet_item.pet_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setPetId(Integer petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_item.pet_name
     *
     * @return the value of pet_item.pet_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getPetName() {
        return petName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_item.pet_name
     *
     * @param petName the value for pet_item.pet_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setPetName(String petName) {
        this.petName = petName == null ? null : petName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_item.pet_description
     *
     * @return the value of pet_item.pet_description
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getPetDescription() {
        return petDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_item.pet_description
     *
     * @param petDescription the value for pet_item.pet_description
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setPetDescription(String petDescription) {
        this.petDescription = petDescription == null ? null : petDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_item.pet_image_url
     *
     * @return the value of pet_item.pet_image_url
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getPetImageUrl() {
        return petImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_item.pet_image_url
     *
     * @param petImageUrl the value for pet_item.pet_image_url
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setPetImageUrl(String petImageUrl) {
        this.petImageUrl = petImageUrl == null ? null : petImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_item.pet_prime_cost
     *
     * @return the value of pet_item.pet_prime_cost
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Long getPetPrimeCost() {
        return petPrimeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_item.pet_prime_cost
     *
     * @param petPrimeCost the value for pet_item.pet_prime_cost
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setPetPrimeCost(Long petPrimeCost) {
        this.petPrimeCost = petPrimeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_item.pet_discount_price
     *
     * @return the value of pet_item.pet_discount_price
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Long getPetDiscountPrice() {
        return petDiscountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_item.pet_discount_price
     *
     * @param petDiscountPrice the value for pet_item.pet_discount_price
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setPetDiscountPrice(Long petDiscountPrice) {
        this.petDiscountPrice = petDiscountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_item.pet_status
     *
     * @return the value of pet_item.pet_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getPetStatus() {
        return petStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_item.pet_status
     *
     * @param petStatus the value for pet_item.pet_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setPetStatus(String petStatus) {
        this.petStatus = petStatus == null ? null : petStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_item.pet_type
     *
     * @return the value of pet_item.pet_type
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getPetType() {
        return petType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_item.pet_type
     *
     * @param petType the value for pet_item.pet_type
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setPetType(String petType) {
        this.petType = petType == null ? null : petType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_item.sale_type
     *
     * @return the value of pet_item.sale_type
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getSaleType() {
        return saleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_item.sale_type
     *
     * @param saleType the value for pet_item.sale_type
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setSaleType(String saleType) {
        this.saleType = saleType == null ? null : saleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_item.contact_way
     *
     * @return the value of pet_item.contact_way
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getContactWay() {
        return contactWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_item.contact_way
     *
     * @param contactWay the value for pet_item.contact_way
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setContactWay(String contactWay) {
        this.contactWay = contactWay == null ? null : contactWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_item.city_no
     *
     * @return the value of pet_item.city_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getCityNo() {
        return cityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_item.city_no
     *
     * @param cityNo the value for pet_item.city_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setCityNo(String cityNo) {
        this.cityNo = cityNo == null ? null : cityNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_item.province_no
     *
     * @return the value of pet_item.province_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getProvinceNo() {
        return provinceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_item.province_no
     *
     * @param provinceNo the value for pet_item.province_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setProvinceNo(String provinceNo) {
        this.provinceNo = provinceNo == null ? null : provinceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_item.district_no
     *
     * @return the value of pet_item.district_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getDistrictNo() {
        return districtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_item.district_no
     *
     * @param districtNo the value for pet_item.district_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setDistrictNo(String districtNo) {
        this.districtNo = districtNo == null ? null : districtNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_item.address
     *
     * @return the value of pet_item.address
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_item.address
     *
     * @param address the value for pet_item.address
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_item.store_id
     *
     * @return the value of pet_item.store_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_item.store_id
     *
     * @param storeId the value for pet_item.store_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_item.create_datetime
     *
     * @return the value of pet_item.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_item.create_datetime
     *
     * @param createDatetime the value for pet_item.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_item.update_datetime
     *
     * @return the value of pet_item.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_item.update_datetime
     *
     * @param updateDatetime the value for pet_item.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}