package org.star_pet_house_commons.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
@TableName(value = "pet_item")
public class PetItem implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.pet_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    @TableId(value = "pet_id", type = IdType.AUTO)
    private Integer pet_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.pet_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String pet_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.pet_description
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String pet_description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.pet_image_url
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String pet_image_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.pet_prime_cost
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Long pet_prime_cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.pet_discount_price
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Long pet_discount_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.pet_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String pet_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.pet_type
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String pet_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.sale_type
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String sale_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.contact_way
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String contact_way;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.city_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String city_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.province_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String province_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.district_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String district_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.address
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.store_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer store_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date create_datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_item.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date update_datetime;
    
}