package org.star_pet_house_commons.model;

import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
@TableName(value = "pet_order")
public class PetOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.order_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    @TableId(value = "order_id")
    private Integer order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.order_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String order_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.title
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.order_note
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String order_note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.sale_user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer sale_user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.sale_order_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String sale_order_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.buy_user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer buy_user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.buy_order_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String buy_order_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.address_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer address_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date create_datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date update_datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.pay_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date pay_datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.pay_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String pay_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.pay_money
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Long pay_money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.prime_cost
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Long prime_cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.pet_type
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String pet_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.pet_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String pet_id;

}