package org.star_pet_house_commons.model;

import java.util.Date;

public class PetOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.order_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.order_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.title
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.order_note
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String orderNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.sale_user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer saleUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.sale_order_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String saleOrderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.buy_user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer buyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.buy_order_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String buyOrderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.address_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.pay_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date payDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.pay_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.pay_money
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Long payMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.prime_cost
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Long primeCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.pet_type
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String petType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_order.pet_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String petId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.order_id
     *
     * @return the value of pet_order.order_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.order_id
     *
     * @param orderId the value for pet_order.order_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.order_no
     *
     * @return the value of pet_order.order_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.order_no
     *
     * @param orderNo the value for pet_order.order_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.title
     *
     * @return the value of pet_order.title
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.title
     *
     * @param title the value for pet_order.title
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.order_note
     *
     * @return the value of pet_order.order_note
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getOrderNote() {
        return orderNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.order_note
     *
     * @param orderNote the value for pet_order.order_note
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setOrderNote(String orderNote) {
        this.orderNote = orderNote == null ? null : orderNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.sale_user_id
     *
     * @return the value of pet_order.sale_user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getSaleUserId() {
        return saleUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.sale_user_id
     *
     * @param saleUserId the value for pet_order.sale_user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setSaleUserId(Integer saleUserId) {
        this.saleUserId = saleUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.sale_order_status
     *
     * @return the value of pet_order.sale_order_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getSaleOrderStatus() {
        return saleOrderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.sale_order_status
     *
     * @param saleOrderStatus the value for pet_order.sale_order_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setSaleOrderStatus(String saleOrderStatus) {
        this.saleOrderStatus = saleOrderStatus == null ? null : saleOrderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.buy_user_id
     *
     * @return the value of pet_order.buy_user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getBuyUserId() {
        return buyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.buy_user_id
     *
     * @param buyUserId the value for pet_order.buy_user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setBuyUserId(Integer buyUserId) {
        this.buyUserId = buyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.buy_order_status
     *
     * @return the value of pet_order.buy_order_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getBuyOrderStatus() {
        return buyOrderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.buy_order_status
     *
     * @param buyOrderStatus the value for pet_order.buy_order_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setBuyOrderStatus(String buyOrderStatus) {
        this.buyOrderStatus = buyOrderStatus == null ? null : buyOrderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.address_id
     *
     * @return the value of pet_order.address_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.address_id
     *
     * @param addressId the value for pet_order.address_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.create_datetime
     *
     * @return the value of pet_order.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.create_datetime
     *
     * @param createDatetime the value for pet_order.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.update_datetime
     *
     * @return the value of pet_order.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.update_datetime
     *
     * @param updateDatetime the value for pet_order.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.pay_datetime
     *
     * @return the value of pet_order.pay_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Date getPayDatetime() {
        return payDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.pay_datetime
     *
     * @param payDatetime the value for pet_order.pay_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setPayDatetime(Date payDatetime) {
        this.payDatetime = payDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.pay_status
     *
     * @return the value of pet_order.pay_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.pay_status
     *
     * @param payStatus the value for pet_order.pay_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus == null ? null : payStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.pay_money
     *
     * @return the value of pet_order.pay_money
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Long getPayMoney() {
        return payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.pay_money
     *
     * @param payMoney the value for pet_order.pay_money
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setPayMoney(Long payMoney) {
        this.payMoney = payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.prime_cost
     *
     * @return the value of pet_order.prime_cost
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Long getPrimeCost() {
        return primeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.prime_cost
     *
     * @param primeCost the value for pet_order.prime_cost
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setPrimeCost(Long primeCost) {
        this.primeCost = primeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.pet_type
     *
     * @return the value of pet_order.pet_type
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getPetType() {
        return petType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.pet_type
     *
     * @param petType the value for pet_order.pet_type
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setPetType(String petType) {
        this.petType = petType == null ? null : petType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_order.pet_id
     *
     * @return the value of pet_order.pet_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_order.pet_id
     *
     * @param petId the value for pet_order.pet_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setPetId(String petId) {
        this.petId = petId == null ? null : petId.trim();
    }
}