package org.star_pet_house_commons.model;

import java.util.Date;

public class PetStore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.store_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.store_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String storeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.store_description
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String storeDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.store_image_url
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String storeImageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.store_score
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Long storeScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.store_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String storeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.province_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String provinceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.city_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String cityNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.distruct_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String distructNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.address
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_store.store_id
     *
     * @return the value of pet_store.store_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_store.store_id
     *
     * @param storeId the value for pet_store.store_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_store.store_name
     *
     * @return the value of pet_store.store_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_store.store_name
     *
     * @param storeName the value for pet_store.store_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_store.store_description
     *
     * @return the value of pet_store.store_description
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getStoreDescription() {
        return storeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_store.store_description
     *
     * @param storeDescription the value for pet_store.store_description
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setStoreDescription(String storeDescription) {
        this.storeDescription = storeDescription == null ? null : storeDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_store.store_image_url
     *
     * @return the value of pet_store.store_image_url
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getStoreImageUrl() {
        return storeImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_store.store_image_url
     *
     * @param storeImageUrl the value for pet_store.store_image_url
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setStoreImageUrl(String storeImageUrl) {
        this.storeImageUrl = storeImageUrl == null ? null : storeImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_store.store_score
     *
     * @return the value of pet_store.store_score
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Long getStoreScore() {
        return storeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_store.store_score
     *
     * @param storeScore the value for pet_store.store_score
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setStoreScore(Long storeScore) {
        this.storeScore = storeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_store.store_status
     *
     * @return the value of pet_store.store_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getStoreStatus() {
        return storeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_store.store_status
     *
     * @param storeStatus the value for pet_store.store_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setStoreStatus(String storeStatus) {
        this.storeStatus = storeStatus == null ? null : storeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_store.user_id
     *
     * @return the value of pet_store.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_store.user_id
     *
     * @param userId the value for pet_store.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_store.province_no
     *
     * @return the value of pet_store.province_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getProvinceNo() {
        return provinceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_store.province_no
     *
     * @param provinceNo the value for pet_store.province_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setProvinceNo(String provinceNo) {
        this.provinceNo = provinceNo == null ? null : provinceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_store.city_no
     *
     * @return the value of pet_store.city_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getCityNo() {
        return cityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_store.city_no
     *
     * @param cityNo the value for pet_store.city_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setCityNo(String cityNo) {
        this.cityNo = cityNo == null ? null : cityNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_store.distruct_no
     *
     * @return the value of pet_store.distruct_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getDistructNo() {
        return distructNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_store.distruct_no
     *
     * @param distructNo the value for pet_store.distruct_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setDistructNo(String distructNo) {
        this.distructNo = distructNo == null ? null : distructNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_store.address
     *
     * @return the value of pet_store.address
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_store.address
     *
     * @param address the value for pet_store.address
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_store.create_datetime
     *
     * @return the value of pet_store.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_store.create_datetime
     *
     * @param createDatetime the value for pet_store.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_store.update_datetime
     *
     * @return the value of pet_store.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_store.update_datetime
     *
     * @param updateDatetime the value for pet_store.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}