package org.star_pet_house_commons.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Data;
import org.star_pet_house_commons.utils.DateStandardFormateSerializer;

import java.io.Serializable;
import java.util.Date;

@Data
@TableName(value = "pet_store")
public class PetStore implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.store_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    @TableId(value = "store_id", type = IdType.AUTO)
    private Integer store_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.store_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String store_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.store_description
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String store_description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.store_image_url
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String store_image_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.store_score
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Long store_score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.store_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String store_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.province_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String province_no;

    @TableField(exist = false)
    private String province_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.city_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String city_no;

    @TableField(exist = false)
    private String city_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.distruct_no
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String district_no;
    @TableField(exist = false)
    private String district_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.address
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    @JsonSerialize(using = DateStandardFormateSerializer.class)
    private Date create_datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_store.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date update_datetime;

    private String application_image;

}