package org.star_pet_house_commons.model;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_image_url
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String userImageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_gender
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String userGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_age
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String userAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_mobile_tel
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String userMobileTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id_card
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String userIdCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_address
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memo
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_image_url
     *
     * @return the value of user_info.user_image_url
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getUserImageUrl() {
        return userImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_image_url
     *
     * @param userImageUrl the value for user_info.user_image_url
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setUserImageUrl(String userImageUrl) {
        this.userImageUrl = userImageUrl == null ? null : userImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_gender
     *
     * @return the value of user_info.user_gender
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getUserGender() {
        return userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_gender
     *
     * @param userGender the value for user_info.user_gender
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setUserGender(String userGender) {
        this.userGender = userGender == null ? null : userGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_age
     *
     * @return the value of user_info.user_age
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_age
     *
     * @param userAge the value for user_info.user_age
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setUserAge(String userAge) {
        this.userAge = userAge == null ? null : userAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_mobile_tel
     *
     * @return the value of user_info.user_mobile_tel
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getUserMobileTel() {
        return userMobileTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_mobile_tel
     *
     * @param userMobileTel the value for user_info.user_mobile_tel
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setUserMobileTel(String userMobileTel) {
        this.userMobileTel = userMobileTel == null ? null : userMobileTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id_card
     *
     * @return the value of user_info.user_id_card
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getUserIdCard() {
        return userIdCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id_card
     *
     * @param userIdCard the value for user_info.user_id_card
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setUserIdCard(String userIdCard) {
        this.userIdCard = userIdCard == null ? null : userIdCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_address
     *
     * @return the value of user_info.user_address
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_address
     *
     * @param userAddress the value for user_info.user_address
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memo
     *
     * @return the value of user_info.memo
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memo
     *
     * @param memo the value for user_info.memo
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_datetime
     *
     * @return the value of user_info.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_datetime
     *
     * @param createDatetime the value for user_info.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.update_datetime
     *
     * @return the value of user_info.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.update_datetime
     *
     * @param updateDatetime the value for user_info.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}