package org.star_pet_house_commons.model;

import java.util.Date;

public class UserAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.address_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.address_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String addressName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.address_type
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String addressType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.address_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String addressStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.address_zipcode
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String addressZipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.mobile_tel
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String mobileTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.consignee
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String consignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.is_default
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.address_id
     *
     * @return the value of user_address.address_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.address_id
     *
     * @param addressId the value for user_address.address_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.address_name
     *
     * @return the value of user_address.address_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getAddressName() {
        return addressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.address_name
     *
     * @param addressName the value for user_address.address_name
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setAddressName(String addressName) {
        this.addressName = addressName == null ? null : addressName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.address_type
     *
     * @return the value of user_address.address_type
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getAddressType() {
        return addressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.address_type
     *
     * @param addressType the value for user_address.address_type
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setAddressType(String addressType) {
        this.addressType = addressType == null ? null : addressType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.address_status
     *
     * @return the value of user_address.address_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getAddressStatus() {
        return addressStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.address_status
     *
     * @param addressStatus the value for user_address.address_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setAddressStatus(String addressStatus) {
        this.addressStatus = addressStatus == null ? null : addressStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.address_zipcode
     *
     * @return the value of user_address.address_zipcode
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getAddressZipcode() {
        return addressZipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.address_zipcode
     *
     * @param addressZipcode the value for user_address.address_zipcode
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setAddressZipcode(String addressZipcode) {
        this.addressZipcode = addressZipcode == null ? null : addressZipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.user_id
     *
     * @return the value of user_address.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.user_id
     *
     * @param userId the value for user_address.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.mobile_tel
     *
     * @return the value of user_address.mobile_tel
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getMobileTel() {
        return mobileTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.mobile_tel
     *
     * @param mobileTel the value for user_address.mobile_tel
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setMobileTel(String mobileTel) {
        this.mobileTel = mobileTel == null ? null : mobileTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.consignee
     *
     * @return the value of user_address.consignee
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.consignee
     *
     * @param consignee the value for user_address.consignee
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.is_default
     *
     * @return the value of user_address.is_default
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.is_default
     *
     * @param isDefault the value for user_address.is_default
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setIsDefault(String isDefault) {
        this.isDefault = isDefault == null ? null : isDefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.create_datetime
     *
     * @return the value of user_address.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.create_datetime
     *
     * @param createDatetime the value for user_address.create_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.update_datetime
     *
     * @return the value of user_address.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.update_datetime
     *
     * @param updateDatetime the value for user_address.update_datetime
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}