package org.star_pet_house_commons.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

@Data
@TableName(value = "wallet")
public class Wallet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet.wallet_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    @TableId(value = "wallet_id", type = IdType.AUTO)
    private Integer wallet_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet.account_balance
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Long account_balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet.wallet_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String wallet_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet.wallet_type
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String wallet_type;

}