package org.star_pet_house_commons.model;

public class Wallet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet.wallet_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer walletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet.account_balance
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private Long accountBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet.wallet_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String walletStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet.wallet_type
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    private String walletType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet.wallet_id
     *
     * @return the value of wallet.wallet_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getWalletId() {
        return walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet.wallet_id
     *
     * @param walletId the value for wallet.wallet_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setWalletId(Integer walletId) {
        this.walletId = walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet.user_id
     *
     * @return the value of wallet.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet.user_id
     *
     * @param userId the value for wallet.user_id
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet.account_balance
     *
     * @return the value of wallet.account_balance
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public Long getAccountBalance() {
        return accountBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet.account_balance
     *
     * @param accountBalance the value for wallet.account_balance
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setAccountBalance(Long accountBalance) {
        this.accountBalance = accountBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet.wallet_status
     *
     * @return the value of wallet.wallet_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getWalletStatus() {
        return walletStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet.wallet_status
     *
     * @param walletStatus the value for wallet.wallet_status
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setWalletStatus(String walletStatus) {
        this.walletStatus = walletStatus == null ? null : walletStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet.wallet_type
     *
     * @return the value of wallet.wallet_type
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public String getWalletType() {
        return walletType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet.wallet_type
     *
     * @param walletType the value for wallet.wallet_type
     *
     * @mbggenerated Mon Mar 30 18:38:12 CST 2020
     */
    public void setWalletType(String walletType) {
        this.walletType = walletType == null ? null : walletType.trim();
    }
}